### ISSUE TITLE
Version clean up error

### ISSUE THREAD

**Issue by simon-tompsett** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#48] opened 2018-04-08 08:27 UTC
This looks a great maintenance  tool but on this installation the version clean up does not delete the versions. First I get an error message (attached), then it says it is complete (attached) but no versions have been deleted?

Using Umbraco 7.7.8 and FALM version 7.7.2.0

Any ideas, is it some kind of database permission issue??

Simon
![falmerror](https://user-images.githubusercontent.com/38177740/38465050-12912102-3b0f-11e8-8f33-fde0ef1bc58f.JPG)
![falmerror2](https://user-images.githubusercontent.com/38177740/38465051-17915eb0-3b0f-11e8-928f-9d6c6f37ee18.JPG)

**Comment by afabri73** [comment] 2018-04-09 12:08
Hi Simon,
thank you for the support.

I found a problem with the UI of Version Manager but no problem found with functionality.
All versions are deleted successfully.
I tested the v7.7.2.0 package with Umbraco v7.7.13 - v7.8.1 - v7.9.3 - v7.10.1

There is still a little problem with the route reloading...so after any deletion, I suggest you to "reload" the page using the button in page or by refresh browser (F5)

In a while I'll publish the updated FALM Housekeeping v7.7.2.1 package.
**_Note: I'll also publish a new version for Umbraco until v7.6.13, so if you want to use my tool with Umbraco from v7.6.0 to v7.6.13 please use this specific FALM Housekeeping version._**

Bye
Adriano

**Comment by simon-tompsett** [comment] 2018-04-09 14:49
Thanks Adriano, I’ll give the new package a try.

Cheers

Simon

**Comment by afabri73** [comment] 2018-04-10 08:02
ok...let me know if you still have problems.

cheers
Adriano

**Comment by simon-tompsett** [comment] 2018-04-10 10:36
Adriano

Still not got this to work. Uninstalled 7.7.2.0 and installed 7.7.2.1. Slightly different response, the error message comes up after a 30 second delay or so, where as it was coming up ‘onClick’.

Suspected the backup system might have been putting a database lock on part way through the process so disabled that but has not resolved the issue.

Can you offer any further help?

Throws a system exception as below
Event

ERROR

Date

10 April 2018

Hour

11:27:09

Process

2460

Domain

12

Thread

58

Logger

System.Exception

Description:
Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding.

**Comment by afabri73** [comment] 2018-04-10 11:02
Sure...I'll try to repilicate your scenario, if I can.
How many versions have that node?

**Comment by simon-tompsett** [comment] 2018-04-10 11:07
I have tried multiple nodes from 3 versions to hundreds of versions, I have also tried cleaning whole site by count and the whole site back to just the two versions. All bring about the same error.

Thanks

Simon

**Comment by afabri73** [comment] 2018-04-10 12:37
I must say that this is the first time I have encountered this kind of issue.
However...before publishing the package I tested it with Umbraco v7.7.13 - v7.8.1 - v7.9.3 - v7.10.1 so considering that your site is made with Umbraco v7.7.8, there shouldn't be any compatibility problems.

I also verified the functionality on my website of fair size (with a number of versions over 20/each node) and I haven't encountered Execution Timeout problems.

BTW...I tried to increase the script timeout to avoid this problem, hoping that this will solve your problem. 
In attach you can find the updated package with the changes so you can do other tests.
If it solve your problem I'll publish it.

I would also like to ask you if you tried to update your Umbraco website to v7.7.13 to exclude compatibility problems with your actual version of Umbraco.

I look forward to your reply
Cheers
Adriano

[FALM_Housekeeping_7.7.2.2.zip](https://github.com/FALM-Umbraco-Projects/FALM-Housekeeping-v7/files/1894560/FALM_Housekeeping_7.7.2.2.zip)

**Comment by simon-tompsett** [comment] 2018-04-10 12:49
Thanks Adriano, I think you forgot to attach the package ☺

The Umbraco instance has not been upgraded since installation

Regards

Simon

**Comment by afabri73** [comment] 2018-04-10 13:01
The package is under my name.
I see it also in your answer

**Comment by simon-tompsett** [comment] 2018-04-10 13:19
Sorry! Loaded that, same two errors logged as below…
Event details
Event

ERROR

Date

10 April 2018

Hour

14:15:37

Process

2460

Domain

21

Thread

97

Logger

Umbraco.Core.Persistence.UmbracoDatabase

Description:
Exception (3a36ee1a).

Event details
Event

ERROR

Date

10 April 2018

Hour

14:15:37

Process

2460

Domain

21

Thread

97

Logger

System.Exception

Description:
Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding.

**Comment by simon-tompsett** [comment] 2018-04-10 14:21
Adriano

Looks like it might just be the time out, I found some nodes with five and less versions, it worked on those, could you give me an extended time out version, or can I control that from here??

Some nodes have up to 2000 versions. The site was coded by one of my team to record clicks on a page, and published every time ☹

Simon

**Comment by afabri73** [comment] 2018-04-10 14:29
ok...I really don't understand...this is my test with a very small website with Umbraco v7.7.8 and MSSQL2014

**_Versions Manager_**
![falmhk-vm1](https://user-images.githubusercontent.com/6714121/38562161-372c94a2-3cda-11e8-83b2-8067e200444d.png)

_**Cleanup by Count**_
![falmhk-vm2](https://user-images.githubusercontent.com/6714121/38562249-6569ace2-3cda-11e8-8278-cde433f1d8a2.png)

_**Cleanup Summary**_
![falmhk-vm3](https://user-images.githubusercontent.com/6714121/38562263-6fd7d0b4-3cda-11e8-92e6-1c43c3848edc.png)

**_And at the end, after clicked on "Restart Search" button:_**
![falmhk-vm4](https://user-images.githubusercontent.com/6714121/38562372-b407a96c-3cda-11e8-871d-ce02a17aabcd.png)

As you can see...no problems found on my website.
I tried also with SQLCE...only to be sure that the problem was not MSSQL, and with 3 other big sites with many versions for each node.

So...I'm sorry but I think that the problem, as you told in a previous post, is on your local installation.
Maybe can be the backup, maybe other...but I think you must search the cause of the problem locally.

When you'll find the cause, I ask you to share it with me

For now I close the issue but can always be re-opened

Cheers
Adriano

**Closed as completed by afabri73** 2018-04-10 14:29 UTC
Labels: help wanted, FIXED, problems during execution
